export { AdminPastoralsPage } from './AdminPastoralsPage'
export { AdminSacramentsPage } from './AdminSacramentsPage'
export { AdminPeoplePage } from './AdminPeoplePage'
export { AdminPrayersPage } from './AdminPrayersPage'
export { AdminMessagesPage } from './AdminMessagesPage'
export { AdminFeastPage } from './AdminFeastPage'
export { AdminSettingsPage } from './AdminSettingsPage'
